### ISSUE TITLE
prevent route from hanging by *always* closing the pg connection

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-postgres-connection#10]
when a route does _not_ make any queries to postgres, do we still need to close the db connection?

this was noted by @Conorc1000 in: https://github.com/OxfordAbstracts/application/issues/197

**Comment by nelsonic** [comment]
Add these 3 lines to index.js

``` js
  server.ext('onPostHandler', function (request, reply) {
    request.pg && request.pg.done && request.pg.done();
    reply.continue();
  })
```

suggested by @rjmk

**Comment by nelsonic** [comment]
trying it now.

**Comment by nelsonic** [comment]
Seeing the following error when running this:

``` sh
Debug: internal, implementation, error
    Error: write EPIPE
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at WriteWrap.afterWrite (net.js:763:14)
```

**Comment by nelsonic** [comment]
@rjmk I _think_ I _may_ have found a simpler solution... :wink:
