### ISSUE TITLE
[1] "name" is required

### ISSUE THREAD

**Issue by Kuchiriel** [dwyl/hapi-postgres-connection#40]
**"hapi": "17.5.4"
"hapi-postgres-connection": "^6.5.1",**

_plugins.js_
```
import Pgc from 'hapi-postgres-connection'

export {
  Pgc
}
```

_server.js_
```
import {
  Pgc
} from './plugins'

await server.register(Pgc)
```

`(node:26700) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Invalid plugin options {
  "plugin": {
    "register": function(server, options, next) {\n\n  server.ext('onPreAuth', function (request, reply) {\n    // each connection created is shut down when the server stops (e.g tests)\n    if(!run_once) {\n      run_once = true;\n      server.on('stop', function () { // only one server.on('stop') listener\n        PG_CON.forEach(function (con) { // close all the connections\n          con && con.client && con.client.readyForQuery && con.client.end();\n          con && con.done && con.done();\n        });\n        server.log(['info', pkg.name], 'DB Connection Closed');\n      });\n    }\n    if(PG_CON.length === 0) {\n      pool.connect(function(err, client, done) {\n        assert(!err, pkg.name + 'ERROR Connecting to PostgreSQL!');\n        PG_CON.push({ client: client, done: done});\n        assign_connection(request, reply);\n      });\n    }\n    else {\n      assign_connection(request, reply);\n    }\n  });\n  next();\n},
    "getCon": function () {\n  return { client: PG_CON[0].client, done: PG_CON[0].done };\n},
    "name" [1]: -- missing --
  }
}

[1] "name" is required
    at new AssertionError (internal/assert.js:268:11)
    at Object.exports.assert (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.apply (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/node_modules/hapi/lib/config.js:22:10)
    at internals.Server.register (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/node_modules/hapi/lib/server.js:399:31)
    at _callee$ (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/src/server.js:32:16)
    at tryCatch (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/src/server.js:15:191)
    at /home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/src/server.js:15:361
(node:26700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:26700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**If I do the following:**

_server.js_

```
  await server.register({
    register: require('hapi-postgres-connection')
  }, () => {})
```

`(node:29308) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Invalid register options "value" must be an object
    at new AssertionError (internal/assert.js:268:11)
    at Object.exports.assert (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.apply (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/node_modules/hapi/lib/config.js:22:10)
    at internals.Server.register (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/node_modules/hapi/lib/server.js:367:26)
    at _callee$ (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/src/server.js:28:16)
    at tryCatch (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/src/server.js:13:191)
    at /home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta/src/server.js:13:361
(node:29308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:29308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by h3w8529** [comment]
this is due to you r using the hapi version 17, this only support hapi version 16

**Comment by Kuchiriel** [comment]
**"hapi": "16.6.2"**

Downgraded, error changed.

`[nodemon] restarting due to changes...
[nodemon] starting `babel-node src/server.js --presets env`
[jwt] route access request 
[jwt] decoded token: undefined
(node:14549) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pg' of undefined
    at Validate (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta-postgres/src/jwt.js:20:11)
    at _callee$ (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta-postgres/src/server.js:33:25)
    at tryCatch (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta-postgres/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta-postgres/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta-postgres/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta-postgres/src/server.js:17:191)
    at /home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta-postgres/src/server.js:17:361
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at Object.<anonymous> (/home/trevor/Projects/CodeRelated/ZionERP_Old/backend-beta-postgres/node_modules/babel-cli/lib/_babel-node.js:154:22)
(node:14549) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14549) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by h3w8529** [comment]
@Kuchiriel, this is not related to **hapi-postgres-connection**

**Comment by Kuchiriel** [comment]
@h3w8529 Hello, do you have any clue how to solve it? Should I open an issue in hapi.js repo?

**Comment by navaladiv** [comment]
@Kuchiriel . Iam also facing this problem for last two days.

msg me if you find a way thank you...
(node:8812) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Invalid plugin options {
  "plugin": {
    "register": function (server, options, next) {\n\n  server.ext('onPreAuth', function (request, reply) {\n    // each connection created is shut down when the server stops (e.g tests)\n    if(!run_once) {\n      run_once = true;\n      server.on('stop', function () { // only one server.on('stop') listener\n
     PG_CON.forEach(function (con) { // close all the connections\n          con && con.client && con.client.readyForQuery && con.client.end();\n          con && con.done && con.done();\n        });\n        server.log(['info', pkg.name], 'DB Connection Closed');\n      });\n    }\n    if(PG_CON.length === 0) {\n      pool.connect(function(err, client, done) {\n        assert(!err, pkg.name + 'ERROR Connecting to PostgreSQL!');\n        PG_CON.push({ client: client,
done: done});\n        assign_connection(request, reply);\n      });\n    }\n    else {\n      assign_connection(request, reply);\n    }\n  });\n  next();\n},
    "getCon": function () {\n  return { client: PG_CON[0].client, done: PG_CON[0].done };\n},
    "name" [1]: -- missing --
  }
}

[1] "name" is required
    at Object.exports.apply (D:\naval\node_modules\hapi\lib\config.js:22:10)
    at internals.Server.register (D:\naval\node_modules\hapi\lib\server.js:399:31)
    at Object.<anonymous> (D:\naval\index.js:28:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
(node:8812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate
the Node.js process with a non-zero exit code.
Server running at: http://localhost:8000

**Comment by Kuchiriel** [comment]
@navaladiv Thanks, if you find before me, msg me, please.

**Comment by Kuchiriel** [comment]
I've downgraded and tested the deps one by one and I've managed to make it work. I will comment here for anyone with the same issue after upgrading hapi.js and hapi.js plugins.

* "blipp": "^2.3.0",
* "boom": "^5.2.0",
* "good": "^7.2.0",
* "good-console": "^6.4.0",
* "good-squeeze": "^5.0.2",
* "hapi": "^16.5.2",
* "hapi-auth-jwt2": "^7.3.0",
* "hapi-cors": "^1.0.1",
* "hapi-postgres-connection": "^6.2.0",
* "joi": "^10.6.0",

The problem seens to be, the newer versions of hapi.js and newers plugins don't work properly with es2018 code style.
